export type Player = {
  id: number;
  characterId: string;
  name: string;
  gender?: string;
  race?: string;
  playerClass?: string;
  isPlaying: boolean;
  isActive?: boolean;
  isStunned?: boolean;
  lvl: number;
  xp: number;
  playerActivity?: string;
  target?: string;
  attackType?: string;
  critType?: string;
  hpMax: number;
  hpActual?: number;
  totalManaBonus?: number;
  mm?: number;
  mmNone?: number;
  mmLeather?: number;
  mmHeavyLeather?: number;
  mmChainmail?: number;
  mmPlate?: number;
  tb?: number;
  tbOffHand?: number;
  dualWield?: number;
  tbUsedForDefense?: number;
  tbOneHanded?: number;
  tb1HSlashing?: number;
  tb1HBlunt?: number;
  tbTwoHanded?: number;
  tbRanged?: number;
  tbUnarmed?: number;
  tbBaseMagic?: number;
  tbTargetMagic?: number;
  armorType?: string;
  vb?: number;
  shield?: boolean;
  agilityBonus?: number;
  mdLenyeg?: number;
  mdKapcsolat?: number;
  perception?: number;
  tracking?: number;
  lockPicking?: number;
  disarmTraps?: number;
  equippedWeaponId?: number | null;
  isAlive?: boolean;
  stunnedForRounds?: number;
  penaltyOfActions?: number;
  hpLossPerRound?: number;
  objectUsage?: number;
  runes?: number;
  influence?: number;
  stealth?: number;
};

export type Weapon = {
  id: number;
  name: string;
  activityType: string;
  attackType: string;
  critType: string;
  secondaryCritType?: string;
  weaponType: string;
  weaponSpecType: string;
  extraTBMH?: number;
  extraTBOH?: number;
  rollCapMH?: number;
  rollCapOH?: number;
  critCapMH?: string;
  critCapOH?: string;
  specialModofierTB?: number;
  manaCost?: number;
  weight?: number;
};

export type PlayerInventoryItem = {
  id: number;
  player: Player;
  weapon: Weapon;
  defaultWeapon: boolean;
};
